select * from customer limit 20
-- Q1. What is the total revenue generated by male vs. female customers?
Select
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer 
where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer WHERE shipping_type IN ('Standard', 'Express') GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, ROUND(AVG(purchase_amount),2) AS average_spend, SUM(purchase_amount) AS total_revenue
FROM customer GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND( SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),2 ) AS discount_percentage
FROM customer GROUP BY item_purchased
ORDER BY discount_percentage DESC LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,and show the count of each segment.
SELECT customer_segment,
COUNT(*) AS total_customers
FROM (
    SELECT
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) t
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM ( SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        DENSE_RANK() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE rnk <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
SELECT subscription_status,
COUNT(*) AS total_customers, ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue 
from customer group by age_group order by total_revenue desc; 
